default:
  SECRET_KEY: "production-secret-key"
  DEBUG: false
  ES_URL: "http://es:9200"
  ES_INDEX_NAME: "inat-photos-index"
  CLIP_MODEL_NAME: "clip-ViT-B-32"
  MEDIAPIPE_HUMAN_DETECT_MODEL: "blaze_face_short_range.tflite"
  HUMAN_EXCLUSION_THRESHOLD: 0.6
  IMAGE_CACHE_DIR: "images/"
  INSERT_BATCH_SIZE: 200
  KNN:
    K: 1_000
    NUM_CANDIDATES: 1_000
  PER_PAGE_DEFAULT: 30