services:

  es:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.1
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 6G

  inatnls:
    container_name: inatnls
    image: inaturalist/inatnls:latest
    restart: always
    ports:
      - 80:5000
    volumes:
      - .htpasswd:/app/.htpasswd
      - app_images_data:/app/images
      - ./logs:/app/logs

volumes:
  es_data:
  app_images_data:
